In [48]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv("50_Startups.csv")

In [8]:
# Prints top 5 rows
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [9]:
# Prints last 5 rows
data.tail()

R&D Spend  Administration  Marketing Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40

In [13]:
# Prints all the column names
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [15]:
# Converting from pandas to 1D array then 2D array.
y = data['Profit'].values.reshape(-1, 1)

In [16]:
# Extracting all the features important for our  target.
X = data[['R&D Spend', 'Administration', 'Marketing Spend', 'State']].values

In [20]:
print(data)
'''
On analyzing dataset we find that there is one feature called 'State' that contains strings in records.
- Label Encoding:
However, Machine Learning algorithm can't process strings so we need to convert these string records into numeric record by replace them different 'Numeric Values'. This process is called Label Encoding. 
'''

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       

"\nOn analyzing dataset we find that there is one feature called 'State' that contains strings in records.\n- Label Encoding:\nHowever, Machine Learning algorithm can't process strings so we need to convert these string records into numeric record by assigning them different 'Numeric Values'. This process is called Label Encoding. \n"

In [22]:
state = data['State']
print(state)

0       New York
1     California
2        Florida
3       New York
4        Florida
5       New York
6     California
7        Florida
8       New York
9     California
10       Florida
11    California
12       Florida
13    California
14       Florida
15      New York
16    California
17      New York
18       Florida
19      New York
20    California
21      New York
22       Florida
23       Florida
24      New York
25    California
26       Florida
27      New York
28       Florida
29      New York
30       Florida
31      New York
32    California
33       Florida
34    California
35      New York
36       Florida
37    California
38      New York
39    California
40    California
41       Florida
42    California
43      New York
44    California
45      New York
46       Florida
47    California
48      New York
49    California
Name: State, dtype: object


In [23]:
# Performing Label Encoding we have Algorithm 
from sklearn.preprocessing import LabelEncoder

In [24]:
state_encoder = LabelEncoder()

In [25]:
state_encoder

LabelEncoder()

In [27]:
state = state_encoder.fit_transform(state)

In [28]:
print(state)

[2 0 1 2 1 2 0 1 2 0 1 0 1 0 1 2 0 2 1 2 0 2 1 1 2 0 1 2 1 2 1 2 0 1 0 2 1
 0 2 0 0 1 0 2 0 2 1 0 2 0]


In [30]:
# sfs

In [32]:
from sklearn.preprocessing import OneHotEncoder
state_Hencoder = OneHotEncoder()

In [36]:
state = state_Hencoder.fit_transform(state.reshape(-1, 1))

In [37]:
type(state)

scipy.sparse.csr.csr_matrix

In [40]:
state = state.toarray()


AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [42]:
state

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [43]:
state = state[:, :2]

In [44]:
state

array([[0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [46]:
X = X[:, :3] 

In [47]:
X

array([[165349.2, 136897.8, 471784.1],
       [162597.7, 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54],
       [144372.41, 118671.85, 383199.62],
       [142107.34, 91391.77, 366168.42],
       [131876.9, 99814.71, 362861.36],
       [134615.46, 147198.87, 127716.82],
       [130298.13, 145530.06, 323876.68],
       [120542.52, 148718.95, 311613.29],
       [123334.88, 108679.17, 304981.62],
       [101913.08, 110594.11, 229160.95],
       [100671.96, 91790.61, 249744.55],
       [93863.75, 127320.38, 249839.44],
       [91992.39, 135495.07, 252664.93],
       [119943.24, 156547.42, 256512.92],
       [114523.61, 122616.84, 261776.23],
       [78013.11, 121597.55, 264346.06],
       [94657.16, 145077.58, 282574.31],
       [91749.16, 114175.79, 294919.57],
       [86419.7, 153514.11, 0.0],
       [76253.86, 113867.3, 298664.47],
       [78389.47, 153773.43, 299737.29],
       [73994.56, 122782.75, 303319.26],
       [67532.53, 105751.03, 304768.73],
       [77044.01, 

In [53]:
X = np.hstack((X, state))


In [54]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [55]:
model.coef_

array([[ 8.06023114e-01, -2.70043196e-02,  2.69798610e-02,
         4.18870191e+01,  2.40675812e+02]])

In [56]:
model.intercept_

array([50083.4568125])