In [2]:
import cv2
import numpy as np

In [3]:
photo = cv2.imread('myphoto.jpg')

In [24]:
def show(image):
    # to open the photo
    cv2.imshow("Hello", image)
    # don't pass anything for opening for forever
    cv2.waitKey()
    # to prevent the program from crashing
    # to close the window, click on the image and press enter.
    cv2.destroyAllWindows()

In [5]:
np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
# Image is a 3D array
photo.shape

(480, 640, 3)

In [7]:
photo

array([[[195, 194, 196],
        [195, 194, 196],
        [195, 194, 196],
        ...,
        [104, 111, 126],
        [101, 107, 126],
        [ 96, 102, 121]],

       [[195, 194, 196],
        [195, 194, 196],
        [195, 194, 196],
        ...,
        [103, 111, 124],
        [101, 108, 125],
        [ 98, 105, 122]],

       [[196, 195, 197],
        [196, 195, 197],
        [195, 194, 196],
        ...,
        [106, 113, 122],
        [104, 110, 123],
        [101, 107, 120]],

       ...,

       [[126, 125, 129],
        [126, 125, 129],
        [126, 125, 129],
        ...,
        [ 82,  86,  97],
        [ 82,  86,  97],
        [ 82,  86,  97]],

       [[126, 124, 130],
        [126, 124, 130],
        [126, 124, 130],
        ...,
        [ 82,  85,  99],
        [ 81,  84,  98],
        [ 81,  84,  98]],

       [[125, 123, 129],
        [125, 123, 129],
        [126, 124, 130],
        ...,
        [ 82,  85,  99],
        [ 81,  84,  98],
        [ 81,  84,  98]]

In [8]:
photo[0]

array([[195, 194, 196],
       [195, 194, 196],
       [195, 194, 196],
       ...,
       [104, 111, 126],
       [101, 107, 126],
       [ 96, 102, 121]], dtype=uint8)

In [9]:
# first picture
photo[0][0]

array([195, 194, 196], dtype=uint8)

In [10]:
# Changing the first pixel to Red
photo[0][0] = [255,0,0]

In [11]:
# croping the  photo
photo_crop = photo[50:500][100:400]

In [13]:
photo

array([[[255,   0,   0],
        [195, 194, 196],
        [195, 194, 196],
        ...,
        [104, 111, 126],
        [101, 107, 126],
        [ 96, 102, 121]],

       [[195, 194, 196],
        [195, 194, 196],
        [195, 194, 196],
        ...,
        [103, 111, 124],
        [101, 108, 125],
        [ 98, 105, 122]],

       [[196, 195, 197],
        [196, 195, 197],
        [195, 194, 196],
        ...,
        [106, 113, 122],
        [104, 110, 123],
        [101, 107, 120]],

       ...,

       [[126, 125, 129],
        [126, 125, 129],
        [126, 125, 129],
        ...,
        [ 82,  86,  97],
        [ 82,  86,  97],
        [ 82,  86,  97]],

       [[126, 124, 130],
        [126, 124, 130],
        [126, 124, 130],
        ...,
        [ 82,  85,  99],
        [ 81,  84,  98],
        [ 81,  84,  98]],

       [[125, 123, 129],
        [125, 123, 129],
        [126, 124, 130],
        ...,
        [ 82,  85,  99],
        [ 81,  84,  98],
        [ 81,  84,  98]]

In [25]:
show(photo)

In [20]:
# zero 3D matrix of 100*100
cn = np.zeros((100,100))

In [21]:
cn.shape

(100, 100)

In [26]:
GPhoto = cv2.cvtColor(photo, cv2.COLOR_BGR2GRAY)

In [27]:
show(GPhoto)